# Generated by Django 2.1 on 2018-10-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEnCobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gescal17', models.CharField(max_length=17)),
                ('municipio', models.CharField(max_length=50)),
                ('tipo_via', models.CharField(max_length=50)),
                ('nombre_via', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('cod_postal', models.CharField(max_length=5)),
                ('uuii', models.IntegerField()),
            ],
            options={
                'ordering': ['tipo_via', 'nombre_via', 'numero'],
            },
        ),
    ]
