# Generated by Django 2.1 on 2018-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coberturatotal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='direccionencobertura',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
