# Generated by Django 2.1 on 2018-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coberturatotal', '0003_auto_20181002_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionencobertura',
            name='numero',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='direccionencobertura',
            name='uuii',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
