# Generated by Django 2.1 on 2018-10-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coberturatotal', '0004_auto_20181002_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
