# Generated by Django 2.1 on 2018-10-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coberturatotal', '0005_ciudad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Importacion',
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='direccionencobertura',
            options={'ordering': ['tipo_via', 'nombre_via', 'numero'], 'verbose_name_plural': 'DireccionesEnCobertura'},
        ),
    ]
