# Generated by Django 2.1 on 2018-10-17 09:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Actuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(help_text='Población', max_length=50)),
                ('actuacion', models.CharField(help_text='Código Actuación', max_length=25)),
                ('idzona', models.CharField(help_text='ID de Zona', max_length=10)),
                ('preparado_fecha', models.DateField(help_text='Fecha Preparado', null=True)),
                ('is_preparado', models.BooleanField(default=False)),
                ('replanteado_fecha', models.DateField(help_text='Fecha Replanteado', null=True)),
                ('is_replanteado', models.BooleanField(default=False)),
                ('aaii_fecha', models.DateField(help_text='Fecha Realización AAII', null=True)),
                ('is_aaii_preparada', models.BooleanField(default=False)),
                ('aaii_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones_aaii_realizadas', to=settings.AUTH_USER_MODEL)),
                ('preparado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones_preparadas', to=settings.AUTH_USER_MODEL)),
                ('replanteado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones_replanteadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Actuaciones',
                'ordering': ['actuacion'],
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gescal17', models.CharField(help_text='GESCAL17', max_length=17, null=True)),
                ('ref_parcela', models.CharField(help_text='Código Catastral', max_length=14)),
                ('nombre_via', models.CharField(help_text='Nombre Vía', max_length=200)),
                ('numero_via', models.CharField(help_text='Número Vía', max_length=5)),
                ('numero_uuii', models.IntegerField(help_text='Número de UUII')),
                ('observaciones', models.CharField(help_text='Observaciones', max_length=200)),
                ('numero_uuii_definitivo', models.IntegerField(help_text='Número de UUII definitivas', null=True)),
                ('resultado_replanteo', models.CharField(choices=[('PREPARADO', 'PREPARADO'), ('VIABLE', 'VIABLE'), ('NO VIABLE', 'NO VIABLE'), ('CONSULTA', 'CONSULTA'), ('NO PROCEDE', 'NO PROCEDE'), ('VOLVER A REPLANTEAR', 'VOLVER A REPLANTEAR'), ('TRAMO 3', 'TRAMO 3'), ('INCIDENCIA', 'INCIDENCIA')], help_text='Resultado Replanteo', max_length=50, null=True)),
                ('estado_aaii', models.CharField(choices=[('NO PROCEDE', 'NO PROCEDE'), ('CONSULTA', 'CONSULTA'), ('OK', 'OK')], help_text='Estado AAII', max_length=50, null=True)),
                ('comentario_gabitel', models.CharField(choices=[('CTO A +120m', 'CTO A +120m'), ('CTO SATURADA', 'CTO SATURADA'), ('DIRECCION REFLEJADA EN COBERTURA TOTAL', 'DIRECCION REFLEJADA EN COBERTURA TOTAL'), ('NO EXISTE FINCA', 'NO EXISTE FINCA'), ('SOLAR', 'SOLAR'), ('PERTENECE A OTRA ACTUACIÓN', 'PERTENECE A OTRA ACTUACIÓN'), ('SIN DOCUMENTOS', 'SIN DOCUMENTOS'), ('OTROS', 'OTROS'), ('CTO NO INSTALADA', 'CTO NO INSTALADA')], help_text='Comentario Gabitel', max_length=100, null=True)),
                ('aclaraciones', models.TextField(help_text='Comentario Gabitel', null=True)),
                ('actuacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actuaciones.Actuacion')),
            ],
            options={
                'verbose_name_plural': 'Fincas',
                'ordering': ['nombre_via', 'numero_via'],
            },
        ),
    ]
