# Generated by Django 2.1 on 2018-10-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actuaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actuacion',
            options={'ordering': ['actuacion'], 'verbose_name': 'Actuación', 'verbose_name_plural': 'Actuaciones'},
        ),
        migrations.AlterField(
            model_name='actuacion',
            name='actuacion',
            field=models.CharField(help_text='Código Actuación', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='actuacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actuaciones.Actuacion', to_field='actuacion'),
        ),
    ]
