# Generated by Django 2.1 on 2018-10-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuaciones', '0002_auto_20181017_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='gescal17',
            field=models.CharField(default='', help_text='GESCAL17', max_length=17),
        ),
    ]
