# Generated by Django 2.1 on 2018-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuaciones', '0004_auto_20181017_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='is_replanteado',
            field=models.BooleanField(default=False),
        ),
    ]
