# Generated by Django 2.1 on 2018-10-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuaciones', '0005_finca_is_replanteado'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='resultado_preparacion',
            field=models.CharField(choices=[('PREPARADO', 'PREPARADO'), ('NO VIABLE', 'NO VIABLE'), ('CONSULTA', 'CONSULTA'), ('NO PROCEDE', 'NO PROCEDE'), ('TRAMO 3', 'TRAMO 3'), ('INCIDENCIA', 'INCIDENCIA')], help_text='Resultado Preparación', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='resultado_replanteo',
            field=models.CharField(choices=[('VIABLE', 'VIABLE'), ('NO VIABLE', 'NO VIABLE'), ('CONSULTA', 'CONSULTA'), ('NO PROCEDE', 'NO PROCEDE'), ('VOLVER A REPLANTEAR', 'VOLVER A REPLANTEAR'), ('TRAMO 3', 'TRAMO 3'), ('INCIDENCIA', 'INCIDENCIA')], help_text='Resultado Replanteo', max_length=50, null=True),
        ),
    ]
